package com.key.tools.member.db.dao;

import com.key.tools.member.db.model.Password;

public interface PasswordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password
     *
     * @mbggenerated
     */
    int insert(Password record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password
     *
     * @mbggenerated
     */
    int insertSelective(Password record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password
     *
     * @mbggenerated
     */
    Password selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Password record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Password record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Password record);
}